version: 3.5.{build}.0
image: Visual Studio 2017
install:
- cmd: git submodule -q update --init
- cmd: |
    cd "C:\Tools\vcpkg"
    git pull > NUL
    .\bootstrap-vcpkg.bat > NUL
    cd %appveyor_build_folder%
before_build:
- cmd: nuget restore
- cmd: vcpkg integrate install
- cmd: vcpkg update
- cmd: vcpkg install spdlog:x86-windows-static spdlog:x64-windows-static detours:x86-windows-static detours:x64-windows-static
- cmd: vcpkg install imgui:x86-windows-static imgui:x64-windows-static
build_script:
- ps: .\build.ps1
after_build:
- ps: |
    Invoke-WebRequest "https://downloads.vigem.org/other/pavel-a/ddverpatch/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe .\bin\x64\Indicium-FW1FontWrapper.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-FW1FontWrapper.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-ImGui.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Indicium-ImGui.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-FW1FontWrapper.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-FW1FontWrapper.dll /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-ImGui.dll "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\Indicium-ImGui.dll /pv "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: 'bin\**\*.dll'
  name: Indicium-Supra
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
cache:
- c:\Tools\vcpkg\installed
